server:
  port: 7000
  address: localhost
  serverAddress: http://47kl032998.zicp.vip
  servlet:
    session:
      cookie:
        path: /
wx:
  information:
    appID: wx93302bba2b8abf69
    appsecret: 0858c610c4e73cd2051ed0f9ba143db2
    templateId: Og7wHyxZy6uRSbHVBs4cz1zfjNTPqb49mHld9I5GPGc #Og7wHyxZy6uRSbHVBs4cz1zfjNTPqb49mHld9I5GPGc #JA81IIX8blVklRcwn84Akf34mxuToK_6bnz_1oKtMCU
    TOKEN: Ginspiration
    authorizedScope: snsapi_base #或snsapi_userinfo,用于获取用户基本信息的方式

save:
  file:
    path: D:/GraduationDesign/save_files_path
spring:
  thymeleaf:
    cache: off
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 10MB
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistics_system?ServerTimeZone=GTM%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#  #redis配置
#  redis:
#    # Redis数据库索引（默认为0）
#    database: 0
#    # redis服务器地址
#    host: 82.157.63.226
#    # redis服务器连接端口
#    port: 6379
#    # redis服务器连接密码（默认为空）
#    password:
#    # 连接超时时间（毫秒）
#    timeout: 5000
#    jedis:
#      pool:
#        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 0 # 连接池中最小空闲连接
#        max-idle: 8 # 连接池中的最大空闲连接