server:
  port: 7999
  address: 127.0.0.1

wechat:
  ui:
    GET_ACCESS_TOKEN_URL: http://localhost:7000/system/getWxAccessToken
save:
  file:
    path: D:/GraduationDesign/save_files_path
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  #配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logistics_system?ServerTimeZone=GTM%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql